server:
  port: 8080

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    각자 PC에 만들어놓은 Database이름을 써야 합니다.
    url: jdbc:mysql://localhost:3306/myreform
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: root
    password: 1212
  thymeleaf:
    cache: false